import Head from 'next/head';
import MainLayout from '../common/layouts/main';

export default function HomePage() {
  return (
    <MainLayout>
      {/* <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <h1>LINKS PAGE</h1>
    </MainLayout>
  );
}
